### ISSUE TITLE
Unclear about parseudpipe's input

### ISSUE THREAD

**Issue by SteffRhes** [ufal/teitok-tools#7]
According to the readme, the `parseudpipe.pl` script: "Takes any tokenized XML file and runs the list of tokens through UDPIPE."

But when I try it with a tokenized xml (generated by udpipe2teitok ) it says "already parsed"

The input file is this: https://github.com/veldhub/veld_chain__demo_teitok-tools/blob/main/data/parseudpipe/in/DEU001_tokenized.xml

And is used in this chain: https://github.com/veldhub/veld_chain__demo_teitok-tools/blob/main/veld_parseudpipe.yaml

To reproduce:
```
git clone --recurse-submodules https://github.com/veldhub/veld_chain__demo_teitok-tools.git
docker compose -f veld_parseudpipe.yaml up
```

**Comment by maartenpt** [comment]
That is not a bug - that is a feature. What udpipe2teitok does is take a text, run it through UDPIPE and then convert the CoNLL-U into TEITOK. So what you end up with is a TEITOK file with UD information inside. The first thing parseudpipe does is check whether it is necessary to parse the file or if it has already been parsed (to avoid overwriting potentially corrected information). So unless you specify `--force`, that is the intended outcome.

**Comment by SteffRhes** [comment]
Okay, fair enough. I'm confused by the description "Takes any tokenized XML file and runs the list of tokens through UDPIPE.", because I interpreted "tokenized XML" to be also "product of udpipe applied on XML" since that produces a "XML with tokens". That's why I tried such a file.

Do you maybe have an example file of a "tokenized XML" that is not "udpipe applied on XML" please?

**Comment by maartenpt** [comment]
The typical set-up is that you take a non-tokenized TEI file, say https://textgridlab.org/1.0/tgcrud-public/rest/textgrid:nw1d.0/data, then run xmltokenize on it to get a tokenized TEI, and then apply tools like runudpipe or nametag.....

**Comment by SteffRhes** [comment]
I see. Thanks for the clarification!
